general_settings: 
  master_key: litellm-my-private-local-key
 
  forward_client_headers_to_llm_api: True

litellm_settings:
  default_max_tokens: 8096
  # set_verbose: true
  ssl_verify: false
  # modify_params: True
  telemetry: True
  drop_params: true # Needed for claude code over github copilot
  turn_off_message_logging: False
  disable_end_user_cost_tracking: True
  enable_json_schema_validation: True

# https://docs.litellm.ai/docs/providers/anthropic
router_settings:
  model_group_alias: {}

include:
  - model_config.yaml
